### PR TITLE
Fix Enter key Event Handling for Submit in Connect Dialog

### LINKED ISSUE #435: Enter key does not submit connect dialog
Fill out the connection dialog (I was using TCP connection, but we should check both work) .
Then hit enter.
The "COnnect" action should be done, but nothing happens and you have to click the button to connect

### PR DESCRIPTION
**Pull request by sundaram123krishnan**
Closes #435

### CODE REVIEW

**Comment by andrewdavidmackenzie** [comment]
When I entered a valid IP and invalid Port, enter didn't seem to do anything.
Later I tried again and it said "Enter port number" (does that mean port was empty, or port was invalid?).
Then I corrected port (see screenshot) and then Enter didn't do anything.

So, there seems to be some logic issue.
Maybe, when an error is displayed, then after fixing it and hitting enter, the error continues to be "set".

After an error being displayed, what would cause it to be unset...
On enter maybe clear the error before trying the validation again?

This screenshots shows an state where the previous error is displayed, but the input values are valid, and Enter does nothing.

Screenshot 2024-09-19 at 9 00 29 PM

**Comment by andrewdavidmackenzie** [comment]
That seemed to fix the interaction. Thanks
Now I'll review code.

File: src/views/connect_dialog_handler.rs [hunk 1]
```diff
@@ -262,7 +266,7 @@ impl ConnectDialog {
                 self.nodeid.clear();
                 #[cfg(feature = "iroh")]
                 self.relay_url.clear();
-                Command::none()
+                text_input::focus(TCP_INPUT_ID.clone())
```
Comment (andrewdavidmackenzie) [inline src/views/connect_dialog_handler.rs:269]: for lines above, do you want/need to clear the other values entered when you switch tabs?
As long as the tab active when COnnect is pressed is the one used in the request - it would all work OK, no?
I know this is previous behaviour but only seen now...

File: src/views/connect_dialog_handler.rs [hunk 2]
```diff
@@ -509,8 +514,15 @@ impl ConnectDialog {
                             .style(CONNECTION_ERROR_DISPLAY.get_text_color()),
                         text("Node Id").size(12),
                         {
-                            let mut node_input =
-                                text_input("Enter node id", &self.nodeid).padding(5);
+                            let mut node_input = text_input("Enter node id", &self.nodeid)
+                                .padding(5)
+                                .id(IROH_INPUT_ID.clone())
```
Comment (andrewdavidmackenzie) [inline src/views/connect_dialog_handler.rs:519]: Could you get the id after creating it, and store it in a Option<Id> field of the class?
Not sure that is much better, more a question.

**Review by andrewdavidmackenzie — APPROVED** [review]
I have a question about alternative to lazy static.
But I will leave to you to decide how best to do it.
Merge when you want!

File: src/views/connect_dialog_handler.rs (hunk 1 above)
Comment (sundaram123krishnan) [reply src/views/connect_dialog_handler.rs:269]: Yes, unless not closed the dialog will not clear the values

File: src/views/connect_dialog_handler.rs (hunk 2 above)
Comment (sundaram123krishnan) [reply src/views/connect_dialog_handler.rs:511]: Just saw some of the examples  having this style of implementation.
So, just thought of following that.
